<template>
  <div class="auth-page">
    <div class="auth-card">
      <div class="auth-header">
        <h2>{{ isLogin ? 'Admin Portal' : 'Register Account' }}</h2>
        <p>{{ isLogin ? 'Sign in to manage university data.' : 'Create a new staff account.' }}</p>
      </div>
      
      <form @submit.prevent="submitForm">
        <div v-if="!isLogin" class="form-group">
          <label for="name">Full Name</label>
          <input type="text" id="name" v-model="form.name" required />
        </div>

        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" id="email" v-model="form.email" required />
        </div>
        
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" v-model="form.password" required />
        </div>

        <div v-if="errorMessage" class="error-message">
          {{ errorMessage }}
        </div>

        <button type="submit" class="btn-submit" :disabled="isLoading">
          {{ isLoading ? 'Processing...' : (isLogin ? 'Login' : 'Register') }}
        </button>
      </form>

      <div class="toggle-text">
        <p v-if="isLogin">
          Don't have an account? <a href="#" @click.prevent="isLogin = false">Register here</a>
        </p>
        <p v-else>
          Already have an account? <a href="#" @click.prevent="isLogin = true">Login here</a>
        </p>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'AuthPage',
  data() {
    return {
      isLogin: true,
      form: {
        name: '',
        email: '',
        password: ''
      },
      isLoading: false,
      errorMessage: ''
    }
  },
  methods: {
    async submitForm() {
      this.isLoading = true;
      this.errorMessage = '';
      
      const endpoint = this.isLogin ? 'http://localhost:8000/api/login' : 'http://localhost:8000/api/register';

      try {
        const response = await axios.post(endpoint, this.form);
        
        // Save the token generated by Laravel
        localStorage.setItem('adminToken', response.data.access_token);
        
        // Redirect to the Admin Dashboard
        this.$router.push('/admin/dashboard');

      } catch (error) {
        if (error.response && error.response.data.message) {
          this.errorMessage = error.response.data.message;
        } else {
          this.errorMessage = 'An error occurred. Please try again.';
        }
      } finally {
        this.isLoading = false;
      }
    }
  }
}
</script>

<style scoped>
.auth-page {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 70vh;
  padding: 40px 15px;
  background-color: #f5f7fa;
}

.auth-card {
  background: #ffffff;
  width: 100%;
  max-width: 400px;
  padding: 40px;
  border-radius: 8px;
  box-shadow: 0 4px 15px rgba(0,0,0,0.1);
}

.auth-header {
  text-align: center;
  margin-bottom: 30px;
}

.auth-header h2 {
  color: #002147;
  margin-bottom: 10px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  font-weight: 600;
  color: #333;
  font-size: 14px;
}

.form-group input {
  width: 100%;
  padding: 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.btn-submit {
  width: 100%;
  padding: 12px;
  background: #002147;
  color: white;
  border: none;
  border-radius: 4px;
  font-weight: 600;
  cursor: pointer;
  margin-top: 10px;
}

.btn-submit:hover {
  background: #f39c12;
}

.error-message {
  color: #e74c3c;
  font-size: 13px;
  margin-top: 10px;
  text-align: center;
}

.toggle-text {
  text-align: center;
  margin-top: 20px;
  font-size: 14px;
}

.toggle-text a {
  color: #f39c12;
  text-decoration: none;
  font-weight: 600;
}
</style>